name: Create/Update Release

on:
    pull_request:
        branches:
            - main
        types:
            - ready_for_review
            - edited
            - labeled

jobs:
    prepare_release:
        name: Prepare Release
        runs-on: ubuntu-latest
        steps:
            - name: Create/Update Draft Release
              if: ${{ github.event.pull_request.draft != true && contains(github.event.pull_request.labels.*.name, 'version-pr') }}
              uses: softprops/action-gh-release@v1
              with:
                  name: ${{ github.event.pull_request.title }}
                  tag: v${{ github.event.pull_request.title }}
                  body: ${{ github.event.pull_request.body }}
                  draft: true
