name: Pull Request

on:
    pull_request:
        branches: ["main", "dev"]

jobs:
    lint_and_prettify:
        name: ESLint And Prettier
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.4.2

            - name: Setup Node
              uses: actions/setup-node@v3.3.0

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: 6.11.0
                  run_install: true

            - name: Run ESLint
              run: pnpm lint

            - name: Run Prettier
              run: pnpx prettier --check .
